pipeline {
    
    agent any 
    
    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        
        stage('Checkout'){
           steps {
                git credentialsId: 'github', 
                url: 'https://github.com/ShubhamSoni-DevOps/cicd-end-to-end.git',
                branch: 'main'
           }
        }

        stage('Build Docker'){
            steps{
                script{
                    sh '''
                    echo 'Buid Docker Image'
                    docker build -t shubhamsonirg/cicd-e2e:${BUILD_NUMBER} .
                    docker image tag shubhamsonirg/cicd-e2e:${BUILD_NUMBER} shubhamsonirg/cicd-e2e:latest
                    '''
                }
            }
        }

        stage('Push the artifacts'){
           steps{
                script{
                    sh '''
                    echo 'Push to Repo'
                    docker push shubhamsonirg/cicd-e2e:${BUILD_NUMBER}
                    docker push shubhamsonirg/cicd-e2e:latest
                    '''
                }
            }
        }
        stage('Remove Unused Images') {
            steps {
                script {
                    sh '''
                    echo "Removing project images..."

                    docker rmi shubhamsonirg/cicd-e2e:${BUILD_NUMBER} || true
                    docker rmi shubhamsonirg/cicd-e2e:latest || true

                    echo "Cleaning dangling images..."
                    docker image prune -f
                    '''
                }
            }
        }
        stage('Checkout K8S manifest SCM'){
            steps {
                git credentialsId: 'github', 
                url: 'https://github.com/ShubhamSoni-DevOps/cicd-demo-manifests-repo.git',
                branch: 'main'
            }
        }
        
        stage('Update K8S manifest'){
            steps {
                script{
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        cat deploy.yaml
                        sed -i "s|shubhamsonirg/cicd-e2e:.*|shubhamsonirg/cicd-e2e:${IMAGE_TAG}|g" deploy.yaml
                        cat deploy.yaml
                        git config --global user.name "shubham"
                        git config --global user.email "cloud@example.com"
                        git add deploy.yaml
                        git commit -m 'Updated the deploy yaml | Jenkins Pipeline'
                        git remote -v
                        '''
                    }
                }
            }
        }
        stage('Push to Repo'){
            steps{
                script{
                    withCredentials([usernamePassword(credentialsId: 'github', passwordVariable: 'GIT_PASSWORD', usernameVariable: 'GIT_USERNAME')]) {
                        sh '''
                        git push https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/ShubhamSoni-DevOps/cicd-demo-manifests-repo.git HEAD:main
                        '''
                    }
                }
            }
        }
    }
}
